// <auto-generated />
using System;
using MagicVillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaApi.Migrations
{
    [DbContext(typeof(MagicVillaContext))]
    partial class MagicVillaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaApi.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicVillaApi.Models.VillaList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SqFt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("VillaList", (string)null);
                });

            modelBuilder.Entity("MagicVillaApi.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Villa_No");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VillaNo"));

                    b.Property<string>("VillaDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Villa_Details");

                    b.Property<int>("VillaId")
                        .HasColumnType("int")
                        .HasColumnName("Villa_Id");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("Villa Number", (string)null);
                });

            modelBuilder.Entity("MagicVillaApi.Models.VillaNumberv2", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VillaNo", "VillaId")
                        .HasName("PK_VillaNumber");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumberv2", (string)null);
                });

            modelBuilder.Entity("MagicVillaApi.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVillaApi.Models.VillaList", "Villa")
                        .WithMany("VillaNumbers")
                        .HasForeignKey("VillaId")
                        .IsRequired()
                        .HasConstraintName("FK_Villa Number_VillaList");

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("MagicVillaApi.Models.VillaNumberv2", b =>
                {
                    b.HasOne("MagicVillaApi.Models.VillaList", "Villa")
                        .WithMany("VillaNumberv2s")
                        .HasForeignKey("VillaId")
                        .IsRequired()
                        .HasConstraintName("FK_VillaNumber_VillaList");

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("MagicVillaApi.Models.VillaList", b =>
                {
                    b.Navigation("VillaNumbers");

                    b.Navigation("VillaNumberv2s");
                });
#pragma warning restore 612, 618
        }
    }
}
